# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przepis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_logo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_receipe',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_title',
            field=models.FileField(upload_to=''),
        ),
    ]
